<a href="https://colab.research.google.com/github/Mohadese-ghayoomi/Assignments-of-DL/blob/main/Assignment1_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import Libraries**

In [ ]:
import tensorflow as tf 
import numpy as np
import os
import matplotlib.pyplot as plt

# **show version of Tensorflow**

In [ ]:
print(tf.__version__)

2.3.0


# **Import one Dataset**

In [ ]:
os.getcwd()

'/content'

In [ ]:
os.chdir('/content/drive/My Drive/Colab Notebooks')

In [ ]:
from datasets import MNISTDataset

# **About Seed**

In [ ]:

tf.random.set_seed(5);
tf.random.normal([4], 0, 1, tf.float32)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-0.18030666, -0.95028627, -0.03964049, -0.7425406 ], dtype=float32)>

In [ ]:
tf.random.set_seed(5);
tf.random.normal([2,2], 0, 1, tf.float32, seed=1 )

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.3768897 , -0.01258316],
       [-0.169515  ,  1.0824056 ]], dtype=float32)>

In [ ]:
#If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.6263931], shape=(1,), dtype=float32)
tf.Tensor([0.7017075], shape=(1,), dtype=float32)


In [ ]:
#If the global seed is set but the operation seed is not set, we get different results for every call to the random op, but the same sequence for every re-run of the program:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2' # the second call uses a different operation seed.

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [ ]:
#If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


In [ ]:
#If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.4243431], shape=(1,), dtype=float32)
tf.Tensor([0.92531705], shape=(1,), dtype=float32)


In [ ]:
#tf.random.stateless_uniform (if run twice with the same seeds and shapes, it will produce the same pseudorandom numbers.)
ints = tf.random.stateless_uniform(
    [10], seed=(2, 3),minval=50, maxval=500, dtype=tf.int32)
print(ints)

tf.Tensor([230 491 136 130 380 231 116 139 356 366], shape=(10,), dtype=int32)


# ***Tesnsorflow***

In [ ]:
#scalar" or "rank-0" tensor
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
#A "vector" or "rank-1" tensor is like a list of values
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [ ]:
#A "matrix" or "rank-2" tensor has 2-axes and we can specify the dtype 
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [ ]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [ ]:
#convert a tensor to a NumPy array with using np.array 
np.array(rank_2_tensor)




array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [ ]:
#convert a tensor to a NumPy array with the tensor.numpy method:
rank_2_tensor.numpy()


array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [ ]:
#The base tf.Tensor class requires tensors to be "rectangular"---that is, along each axis, every element is the same size.
# However, there are specialized types of tensors that can handle different shapes:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [ ]:
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [ ]:
#Tensors are used in all kinds of operations (ops).

c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [ ]:
#Shape: The length (number of elements) of each of the dimensions of a tensor.
#Rank: Number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
#Axis or Dimension: A particular dimension of a tensor.
#Size: The total number of items in the tensor, the product shape vector
rank_4_tensor = tf.zeros([3,2, 4, 5])
print(rank_4_tensor)
print('--------------------------------------------------------------- ')
print("Type of every element:", rank_4_tensor.dtype)
print("Number of dimensions:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(3, 2, 4, 5), dtype=float32)
--------------------------------------------------------------- 
Type of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


In [ ]:
#Indexing
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

[ 0  1  1  2  3  5  8 13 21 34]
First: 0
Second: 1
Last: 34
Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


In [ ]:
#Multi-axis indexing
print(rank_2_tensor.numpy())
# Pull out a single value from a 2-rank tensor
print(rank_2_tensor[1, 1].numpy())
# Get row and column tensors
print("Second row:", rank_2_tensor[1, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")

[[1. 2.]
 [3. 4.]
 [5. 6.]]
4.0
Second row: [3. 4.]
Second column: [2. 4. 6.]
Last row: [5. 6.]
First item in last column: 2.0
Skip the first row:
[[3. 4.]
 [5. 6.]] 



In [ ]:
#3-axis tensor
print(rank_3_tensor)
print('-------------------------- --------------')
print(rank_3_tensor[:, :, 4])


tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
-------------------------- --------------
tf.Tensor(
[[ 4  9]
 [14 19]
 [24 29]], shape=(3, 2), dtype=int32)


In [ ]:
#Manipulating Shapes
# Shape returns a `TensorShape` object that shows the size on each dimension
x = tf.constant([[1], [2], [3]])
print(x.shape)
# You can convert this object into a Python list, too
print(x.shape.as_list())
# You can reshape a tensor to a new shape.
# Note that you're passing in a list
reshaped = tf.reshape(x, [1, 3])
print(x.shape)
print(reshaped.shape)

(3, 1)
[3, 1]
(3, 1)
(1, 3)


In [ ]:
#The data maintains its layout in memory and a new tensor is created,
#with the requested shape, pointing to the same data. TensorFlow uses C-style "row-major" memory ordering,
#where incrementing the rightmost index corresponds to a single step in memory.
print(rank_3_tensor)

#If you flatten a tensor you can see what order it is laid out in memory.
print('--------------------------------------------------------------')
print(tf.reshape(rank_3_tensor, [-1]))

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
--------------------------------------------------------------
tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)


In [ ]:
#Typically the only reasonable uses of tf.reshape are to combine or split adjacent axes (or add/remove 1s).
#For this 3x2x5 tensor, reshaping to (3x2)x5 or 3x(2x5) are both reasonable things to do, as the slices do not mix:
print(tf.reshape(rank_3_tensor, [3*2, 5]), "\n")
print(tf.reshape(rank_3_tensor, [3, -1]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


In [ ]:
#Reshaping will "work" for any new shape with the same total number of elements, but it will not do anything useful if you do not respect the order of the axes.
#Swapping axes in tf.reshape does not work, you need tf.transpose for that.
# Bad examples: don't do this

# You can't reorder axes with reshape.
print(tf.reshape(rank_3_tensor, [2, 3, 5]), "\n") 

# This is a mess
print(tf.reshape(rank_3_tensor, [5, 6]), "\n")

# This doesn't work at all
try:
  tf.reshape(rank_3_tensor, [7, -1])
except Exception as e:
  print(f"{type(e).__name__}: {e}")

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]], shape=(2, 3, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]], shape=(5, 6), dtype=int32) 

InvalidArgumentError: Input to reshape is a tensor with 30 values, but the requested shape requires a multiple of 7 [Op:Reshape]


In [ ]:
#cast from type to type
the_f64_tensor = tf.constant([2.2, 3.3, 4.4])
print(the_f64_tensor)
the_f16_tensor = tf.cast(the_f64_tensor ,dtype=tf.float16)
print(the_f16_tensor)
the_u8_tensor = tf.cast(the_f16_tensor, dtype=tf.uint8)
print(the_u8_tensor)

tf.Tensor([2.2 3.3 4.4], shape=(3,), dtype=float32)
tf.Tensor([2.2 3.3 4.4], shape=(3,), dtype=float16)
tf.Tensor([2 3 4], shape=(3,), dtype=uint8)


In [ ]:
# Braodcasting
#Broadcasting is a concept borrowed from the equivalent feature in NumPy. In short, under certain conditions,
#smaller tensors are "stretched" automatically to fit larger tensors when running combined operations on them.
#The simplest and most common case is when you attempt to multiply or add a tensor to a scalar. In that case,
#the scalar is broadcast to be the same shape as the other argument.
x = tf.constant([1, 2, 3])
y = tf.constant(2)
z = tf.constant([2, 2, 2])
# All of these are the same computation
print(tf.multiply(x, 2))
print(x * y)
print(x * z)
print('---------------------------------------' , "\n")
x = tf.constant([[1, 2, 3],[1,3,4]])
y = tf.constant(2)
z = tf.constant([[2, 2, 2],[2,2,2]])
# All of these are the same computation
m = tf.reshape(z,[3,2])
print(m, "\n")
print(x * y, "\n")
print(x * z , "\n")
print(tf.matmul(x, m))

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
--------------------------------------- 

tf.Tensor(
[[2 2]
 [2 2]
 [2 2]], shape=(3, 2), dtype=int32) 

tf.Tensor(
[[2 4 6]
 [2 6 8]], shape=(2, 3), dtype=int32) 

tf.Tensor(
[[2 4 6]
 [2 6 8]], shape=(2, 3), dtype=int32) 

tf.Tensor(
[[12 12]
 [16 16]], shape=(2, 2), dtype=int32)


In [ ]:
#Likewise, 1-sized dimensions can be stretched out to match the other arguments. Both arguments can be stretched in the same computation.
#In this case a 3x1 matrix is element-wise multiplied by a 1x4 matrix to produce a 3x4 matrix. Note how the leading 1 is optional: The shape of y is [4].
# These are the same computations
x = tf.constant([1, 2, 3])
x = tf.reshape(x,[3,1])
y = tf.range(1, 5)
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


In [ ]:
# without broadcasting 
#Here is the same operation without broadcasting:
x_stretch = tf.constant([[1, 1, 1, 1],
                         [2, 2, 2, 2],
                         [3, 3, 3, 3]])

y_stretch = tf.constant([[1, 2, 3, 4],
                         [1, 2, 3, 4],
                         [1, 2, 3, 4]])

print(x_stretch * y_stretch)  # Again, operator overloading

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


In [ ]:
#what broadcasting looks like using tf.broadcast_to
print(tf.broadcast_to(tf.constant([1, 2, 3]), [6, 3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]], shape=(6, 3), dtype=int32)


In [ ]:
#Ragged Tensors
#A tensor with variable numbers of elements along some axis is called "ragged". Use tf.ragged.RaggedTensor for ragged data.
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]
try:
  tensor = tf.constant(ragged_list)
except Exception as e:
  print(f"{type(e).__name__}: {e}")

ValueError: Can't convert non-rectangular Python sequence to Tensor.


In [ ]:
#Instead create a tf.RaggedTensor using tf.ragged.constant:
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)
# shape of ragged_tensor
print(ragged_tensor.shape)


<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>
(4, None)


In [ ]:
#String tensors

# **tf.variable**

In [ ]:
#A TensorFlow variable is the recommended way to represent shared, persistent state your program manipulates. 
#Variables are created and tracked via the tf.Variable class. A tf.Variable represents a tensor whose value can be changed by running ops on it. 
#Specific ops allow you to read and modify the values of this tensor.

In [ ]:
#Create a variable
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
my_variable = tf.Variable(my_tensor)

# Variables can be all kinds of types, just like tensors
bool_variable = tf.Variable([False, False, False, True])
complex_variable = tf.Variable([5 + 4j, 6 + 1j])

In [ ]:
# variable looks and acts like a tensor, and, in fact, is a data structure backed by a tf.Tensor. 
#Like tensors, they have a dtype and a shape, and can be exported to NumPy.
print("Shape: ", my_variable.shape)
print("DType: ", my_variable.dtype)
print("As NumPy: ", my_variable.numpy())

Shape:  (2, 2)
DType:  <dtype: 'float32'>
As NumPy:  [[1. 2.]
 [3. 4.]]


In [ ]:
# Most tensor operations work on variables as expected, although variables cannot be reshaped.
print("A variable:", my_variable)
print("\nViewed as a tensor:", tf.convert_to_tensor(my_variable))
print("\nIndex of highest value:", tf.argmax(my_variable))

# This creates a new tensor; it does not reshape the variable.
print("\nCopying and reshaping: ", tf.reshape(my_variable, ([1,4])))

A variable: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

Viewed as a tensor: tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

Index of highest value: tf.Tensor([1 1], shape=(2,), dtype=int64)

Copying and reshaping:  tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)


In [ ]:
#reassign the tensor using tf.Variable.assign. Calling assign does not (usually) allocate a new tensor; instead, the existing tensor's memory is reused.
a = tf.Variable([2.0, 3.0])
print(a)
# This will keep the same dtype, float32
print(a.assign([1, 2]))
# Not allowed as it resizes the variable: 
try:
  a.assign([1.0, 2.0, 3.0])
except Exception as e:
  print(f"{type(e).__name__}: {e}")

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>
<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>
ValueError: Shapes (2,) and (3,) are incompatible


In [ ]:
#Creating new variables from existing variables duplicates the backing tensors. Two variables will not share the same memory.
a = tf.Variable([2.0, 3.0])
# Create b based on the value of a
b = tf.Variable(a)
a.assign([5, 6])

# a and b are different
print(a.numpy())
print(b.numpy())

# There are other versions of assign
print(a.assign_add([2,3]).numpy())  # [7. 9.]
print(a.assign_sub([7,9]).numpy())  # [0. 0.]



[5. 6.]
[2. 3.]
[7. 9.]
[0. 0.]


In [ ]:
#In Python-based TensorFlow, tf.Variable instance have the same lifecycle as other Python objects. When there are no references to a variable it is automatically deallocated.
#Variables can also be named which can help you track and debug them. You can give two variables the same name.
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
# Create a and b; they will have the same name but will be backed by
# different tensors.
a = tf.Variable(my_tensor, name="Mark")
print(a)
# A new variable with the same name, but different value
# Note that the scalar add is broadcast
b = tf.Variable(my_tensor+1 , name="Mark")
print(b)
# These are elementwise-unequal, despite having the same name
print(a == b)


<tf.Variable 'Mark:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>
<tf.Variable 'Mark:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>
tf.Tensor(
[[False False]
 [False False]], shape=(2, 2), dtype=bool)


In [ ]:
v = tf.Variable(1.)
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>

In [ ]:
v.assign(2.)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=2.0>

In [ ]:
v.assign_add(0.5)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=2.5>

In [ ]:
v.assign_sub(2)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=0.5>

In [ ]:
v = tf.Variable(1., shape=tf.TensorShape(None))
v.assign([[1.]])

<tf.Variable 'UnreadVariable' shape=<unknown> dtype=float32, numpy=array([[1.]], dtype=float32)>

In [ ]:
w = tf.Variable([[1.], [2.]])
x = tf.constant([[3., 4.]])
tf.matmul(w, x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [6., 8.]], dtype=float32)>

In [ ]:
tf.add(w, x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 5.],
       [5., 6.]], dtype=float32)>

In [ ]:
tf.sigmoid(w + x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.98201376, 0.9933071 ],
       [0.9933071 , 0.99752736]], dtype=float32)>

In [ ]:
print(tf.add([[1, 2, 0],[1,2,5]], [[3, 4, 5],[3,5,3]]))

tf.Tensor(
[[4 6 5]
 [4 7 8]], shape=(2, 3), dtype=int32)


In [ ]:
x = tf.add([1, 2], [3, 4])
print(x)
print(x.shape)



tf.Tensor([4 6], shape=(2,), dtype=int32)
(2,)


# **Nupmy**

In [ ]:
import numpy as np

ndarray = np.ones([3, 3])

print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(ndarray, 42)
print(tensor)


print("And NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And NumPy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [ ]:
x = tf.random.uniform([3, 3])

print("Is there a GPU available: "),
print(tf.config.experimental.list_physical_devices("GPU"))

print("Is the Tensor on GPU #0:  "),
print(x.device.endswith('GPU:0'))

Is there a GPU available: 
[]
Is the Tensor on GPU #0:  
False


In [ ]:
a = np.array([[8,1,6],[8,1,6],[8,1,6]])
b = np.array([[7,2,2],[8,1,6],[8,1,3]])
c = a*b
print(c)
print(a.shape)
print(b.shape)

[[56  2 12]
 [64  1 36]
 [64  1 18]]
(3, 3)
(3, 3)


In [ ]:
a = np.matrix([[8,6],[2,4]])
b= np.matrix([[7,2],[5,5]])
c= a*b
print(c)


[[86 46]
 [34 24]]


In [ ]:
print(np.dot(a,b))

[[86 46]
 [34 24]]


In [ ]:
a = np.array([256,256,3])
b= 3
c= a*b
print(c)

[768 768   9]


In [ ]:
 x= np.array([[12,7,3],[12,7,3],[12,7,3]])
print(x.shape)

(3, 3)


In [ ]:
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [ ]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
b = tf.variable_creator_scope(np.zeros([10]))
print(b)

In [ ]:
x = tf.constant([1,3,4])
x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 4], dtype=int32)>

In [ ]:
w=tf.random.normal([1,3])
w

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1.1468066 , 0.96459925, 0.87830144]], dtype=float32)>

In [ ]:
#http://www.projelecom.ir/2018/08/21/%d8%b4%d8%b1%d9%88%d8%b9-%d8%a8%d9%87-%d8%a7%d8%b3%d8%aa%d9%81%d8%a7%d8%af%d9%87-%d8%a7%d8%b2-%da%a9%d8%aa%d8%a7%d8%a8%d8%ae%d8%a7%d9%86%d9%87-numpy-%d8%af%d8%b1-%d9%be%d8%a7%db%8c%d8%aa%d9%88%d9%86/

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))
print(Z.size)
print(Z.itemsize)

800 bytes
100
8


In [ ]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [ ]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [ ]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.9789358  0.14326439 0.15774863]
  [0.64009937 0.03539458 0.97428542]
  [0.26875201 0.28982658 0.34707366]]

 [[0.25450706 0.32905994 0.23628539]
  [0.5777372  0.7812877  0.38279841]
  [0.11214424 0.30331192 0.83385136]]

 [[0.60937133 0.37917787 0.79685839]
  [0.65951182 0.82662914 0.73500126]
  [0.80263579 0.01061178 0.18730975]]]


In [ ]:
#Max and Min of random Vector 
Z = np.random.random((10,10))
print(Z)
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

[[0.75661549 0.16135045 0.08957807 0.30653896 0.29420047 0.66834485
  0.99154762 0.13653099 0.02152753 0.08990968]
 [0.08016174 0.43999115 0.13250694 0.85843548 0.35449436 0.8442137
  0.12016131 0.83725723 0.13622255 0.51280345]
 [0.95086587 0.62417084 0.32695893 0.87304167 0.33285704 0.54559199
  0.09302585 0.2446828  0.08585572 0.0414752 ]
 [0.36698214 0.65397697 0.95129053 0.66154461 0.70678874 0.35893243
  0.38266231 0.99248437 0.38103531 0.81524195]
 [0.28257315 0.66445056 0.68438078 0.7897688  0.70144756 0.32606342
  0.41450104 0.04122119 0.30291892 0.15312536]
 [0.65870066 0.65527995 0.41762874 0.76509541 0.91385211 0.69776533
  0.03515784 0.96699399 0.28912828 0.18435773]
 [0.54713142 0.92867745 0.26657859 0.73898252 0.27484917 0.88061901
  0.7712138  0.12852817 0.5381674  0.36600639]
 [0.60782747 0.2574456  0.92599492 0.05799297 0.34934865 0.9843687
  0.85922069 0.67332157 0.30912193 0.73750088]
 [0.09152709 0.93161772 0.79671497 0.4549314  0.91452523 0.23209383
  0.9014238  0

In [ ]:
# mean of random vector
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5201747937665023


In [ ]:
# two dimensional array with 1 in margin value and zero in internal values 
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
#two dimensional array with 0 in margin value and 1 in internal values
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)



[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [ ]:
x = np.arange(4)
print(x)
xx = x.reshape(4,1)
print(xx)
y = np.ones(5)
print(y)
z = np.ones((3,4))
print(z)

[0 1 2 3]
[[0]
 [1]
 [2]
 [3]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
print(x.shape)

print(y.shape)
##print(x + y)
##ValueError: operands could not be broadcast together with shapes (4,) (5,)

print(xx.shape)

print(y.shape)

print((xx + y).shape)

print(xx + y)
print( x.shape)

print(z.shape)

print((x + z).shape)

print(x + z)


(4,)
(5,)
(4, 1)
(5,)
(4, 5)
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
(4,)
(3, 4)
(3, 4)
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [ ]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
# we can use reshape operator 
A=a.reshape(4,1)
print(A+b)
print('-----------------')
#Or we can use newaxis operator
print(a[:, np.newaxis] + b) 

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
-----------------
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]



# **Gradients and Automatic Differentiation**

In [ ]:
#Computing gradients
#To differentiate automatically, TensorFlow needs to remember what operations happen in what order during the forward pass.
#Then, during the backward pass, TensorFlow traverses this list of operations in reverse order to compute gradients.
tf.GradientTape(
    persistent=False, watch_accessed_variables=True
)

x = tf.constant(3.0)
with tf.GradientTape() as g:
#Operations are recorded if they are executed within this context manager and at least one of their inputs is being "watched".
#Trainable variables (created by tf.Variable or tf.compat.v1.get_variable, where trainable=True is default in both cases) are automatically watched.
#Tensors can be manually watched by invoking the watch method on this context manager.
  g.watch(x)
  y = x * x
dy_dx = g.gradient(y, x) # Will compute to 6.0
print("dy_dx =" , dy_dx.numpy())

x = tf.constant(3.0)
with tf.GradientTape() as g:
  g.watch(x)
  with tf.GradientTape() as gg:
    gg.watch(x)
    y = x * x
  dy_dx = gg.gradient(y, x) # Will compute to 6.0
  print("dy_dx =" , dy_dx.numpy())
d2y_dx2 = g.gradient(dy_dx, x)  # Will compute to 2.0
print("d2y_dx2 =" , d2y_dx2.numpy())

dy_dx = 6.0
dy_dx = 6.0
d2y_dx2 = 2.0


In [ ]:
#To compute multiple gradients over the same computation, create a persistent gradient tape.
#This allows multiple calls to the gradient() method as resources are released when the tape object is garbage collected.
x = tf.constant(3.0)
with tf.GradientTape(persistent=True) as g:
  g.watch(x)
  y = x * x
  z = y * y
dz_dx = g.gradient(z, x)  # 108.0 (4*x^3 at x = 3)
dy_dx = g.gradient(y, x)  # 6.0
print("dz_dx =" , dz_dx.numpy())
print("dy_dx =" , dy_dx.numpy())
del g  # Drop the reference to the tape

dz_dx = 108.0
dy_dx = 6.0


In [ ]:
#y default GradientTape will automatically watch any trainable variables that are accessed inside the context.
#If you want fine grained control over which variables are watched you can disable automatic tracking by passing watch_accessed_variables=False to the tape constructor:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
B = tf.constant(3.0)
L = tf.constant(9.0)
with tf.GradientTape(persistent=True, watch_accessed_variables=False) as tape:
  tape.watch(B)
  tape.watch(L)

  C = B ** 2  # Gradients will be available for `variable_a`.
  V =L ** 3  # No gradients will be available since `variable_b` is not being watched.
  G1 = tape.gradient(C,B)
  G2 = tape.gradient(V ,L)
  print("G1 =" , G1.numpy())
  print("G2 =" , G2.numpy())



G1 = 6.0
G2 = 243.0


In [ ]:
w = tf.Variable(tf.random.normal((3, 2)), name='w')
print(w)
b = tf.Variable(tf.zeros(2, dtype=tf.float32), name='b')
print(b.numpy())
x = [[1., 2., 3.]]
print(x)
with tf.GradientTape(persistent=True) as tape:
  y = x @ w + b
  print(y.numpy())

<tf.Variable 'w:0' shape=(3, 2) dtype=float32, numpy=
array([[ 0.80348307, -0.36864725],
       [-0.76201993, -0.34643286],
       [-0.87193286, -1.3989494 ]], dtype=float32)>
[0. 0.]
[[1.0, 2.0, 3.0]]
[[-3.3363554 -5.258361 ]]
